### PR TITLE
[chore] Bump @tableland/evm

### PR DESCRIPTION
**Pull request by avichalp**
## Summary

Updates the version of tableland/evm package which supports Arbitrum sepolia instead of arbitrum goerli

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by avichalp** [comment]
@sanderpick didn't update local-tableland because it was using an older version. will wait for @joewagner's input on that. also Joe, could you please help up publish a new release?

**Comment by joewagner** [comment]
> should this be updated to?
> 
> https://github.com/tablelandnetwork/tableland-js/blob/2fcc8a01f8556622811e27d3d7f9a24f0c443e88/packages/local/registry/package.json#L8
> 
> cc @joewagner

Yes good call, we should also bump the `local` registry dep.

**Comment by joewagner** [comment]
We are going to want to publish `@tableland/local` and `@tableland/sdk` with new versions.  Do we know what kind of bump this is? patch, minor, or major?

**Comment by avichalp** [comment]
@joewagner perhaps minor since we are updating `@tableland/evm` from `4.4.0` to `4.5.0`?

**Review by sanderpick — DISMISSED** [review]

**Review by joewagner — APPROVED** [review]

**Pull request merged**
